name: Referrals
version: 1.0
main: com.me4502.referrals.spigot.ReferralsSpigot
authors: [Me4502]
description: Referrals plugin for Spigot
commands:
   referral:
      description: Base referrals command.
      usage: /<command> [player|website|list|delete|reload] <source>
      permission: referral.referral
      permission-message: You don't have <permission>